---
- name: Descargar Prestashop
  unarchive:
    src: "{{ prestashop_url_download }}"
    dest: "{{ prestashop_root_path }}"
    remote_src: True
    owner: www-data
    group: www-data
    creates: "{{ prestashop_root_path }}/prestashop-installed"

- name: Fijamos permisos de la instalación de Prestashop
  file:
    path: "{{ prestashop_root_path }}"
    mode: 0775
    recurse: yes
    state: directory
    owner: www-data
    group: www-data
  notify: Recargar Nginx

- name: Descomprimimos el zip de Prestashop
  unarchive:
    src: "{{ prestashop_root_path }}/prestashop.zip"
    dest: "{{ prestashop_root_path }}"
    owner: www-data
    group: www-data
    creates: "{{ prestashop_root_path }}/prestashop-installed"