---
- name: Comprobamos si ya está instalado PrestaShop.
  stat:
    path: "{{ prestashop_root_path }}/{{ prestashop_check_file_name }}"
  register: prestashop_status

- name: Creamos el directorio de PrestaShop.
  file:
    path: "{{ prestashop_root_path }}"
    owner: www-data
    group: www-data
    mode: 0755
    state: directory
  when: prestashop_status.stat.exists == false

- name: Descargamos Prestashop.
  unarchive:
    src: "{{ prestashop_url_download }}"
    dest: "{{ prestashop_root_path }}"
    remote_src: true
    owner: www-data
    group: www-data
  when: prestashop_status.stat.exists == false

- name: Descomprimimos el zip de Prestashop.
  unarchive:
    src: "{{ prestashop_root_path }}/prestashop.zip"
    dest: "{{ prestashop_root_path }}"
    remote_src: true
    owner: www-data
    group: www-data
  when: prestashop_status.stat.exists == false

- name: Borramos el zip de Prestashop.
  file:
    state: absent
    path: "{{ prestashop_root_path }}/prestashop.zip"
  when: prestashop_status.stat.exists == false

- name: Instalamos Prestashop desde consola.
  command: "php7.1 index_cli.php --domain={{ prestashop_domain }} --db_create={{ prestashop_db_create }} --db_server={{ prestashop_db_server }} --db_name={{ prestashop_db_name }} --db_user={{ prestashop_db_user }} --db_password={{ prestashop_db_password }} --engine={{ prestashop_db_engine }} --prefix={{ prestashop_db_prefix }} --language={{ prestashop_language }} --country={{ prestashop_country }} --timezone={{ prestashop_timezone }} --firstname={{ prestashop_firstname }} --lastname={{ prestashop_lastname }} --password={{ prestashop_password }} --email={{ prestashop_email }} --newsletter={{ prestashop_newsletter }}"
  args:
    chdir:  "{{ prestashop_root_path }}/install"
  when: prestashop_status.stat.exists == false

- name: Borramos el directorio install de PrestaShop.
  file:
    path: "{{ prestashop_root_path }}/install"
    state: absent

- name: Renombramos el directorio admin de PrestaShop.
  command: "mv {{ prestashop_root_path }}/admin {{ prestashop_root_path }}/{{ prestashop_admin_folder_name }}"
  when: prestashop_status.stat.exists == false

- name: Creamos archivo que indica que PrestsSop está instalado.
  copy:
    content: "PrestaShop {{ prestashop_version }} instalado, no borrar este archivo, sino Ansible volverá a reinstalar PrestaShop"
    dest: "{{ prestashop_root_path }}/{{ prestashop_check_file_name }}"
  when: prestashop_status.stat.exists == false